########## ???? (JVM ????? ??? local? ??) ##########
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration  #support ? ???? ?? ?? ????

  ########## JPA ##########
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false  #?????? ???? ??
    open-in-view: false  #????? view?? ???? ?? -> ?? ??
    show-sql: false  #???? (local? ????)

    ########## hibernate ##########
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #?????? ?? ?????.
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      #??? ??? ??(physical_naming_strategy) ??.. ? ??. ??? ????/???? ??? ???? ??? ???
      ddl-auto: update

    properties:
      hibernate:
        default-batch-fetch-size: 1000 #?? ??? ?? ??. ???? 1000?? ??
        #format_sql: true
        order_inserts: true # ? ??? ??? statement? ????? commit ??? ?? ?? ???.
        order_updates: true # ? ??? ??? statement? ????? commit ??? ?? ?? ???.
        jdbc:
          batch_size: 200  #x?? ???? ??? ??. 5~30 ?? ????? ?. ?? ?? ????
          #batch_versioned_data: true #?? ??? ?? int? ???

  data:
    web:
      pageable:
        default-page-size: 100 #?? ??? ??? (? ?? ??. ???? ????)

#  security:
#    filter:
#      dispatcher-types:
#        - request
#        - error

########### ?? ???? ##########
logging:
  pattern:
    console: "%date{'yyyy-MM-dd HH:mm:ss','Asia/Seoul'} %-5level %-35logger{5} %3L %msg %n"
  level:
    root: warn
    org.hibernate: warn  # StatisticalLoggingSessionEventListener ? info ??
    org.hibernate.SQL: warn #?? ???? INFO?
    org.springframework.security: warn
    com.epe.barogo: info